version: "3"

services:
  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 2019:2019
      - 443:443
    volumes:
      - ./index.html:/usr/share/caddy/index.html
      - ./assets:/usr/share/caddy/assets
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
