version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "88:15:7f:4a:1b:1e:12:9c:ab:e7:af:12:bc:d8:25:01"
      - checkout
      - run:
          command: scp -o StrictHostKeyChecking=no ./scripts/deploy.sh ./scripts/env.sh docker-compose.yml index.html Caddyfile ${DO_USER}@${DO_HOST}:~
      - run:
          command: scp -r -o StrictHostKeyChecking=no ./nginx ./assets ${DO_USER}@${DO_HOST}:~
      - run:
          command: ssh -o StrictHostKeyChecking=no ${DO_USER}@${DO_HOST} "/bin/bash ./deploy.sh"
workflows:
  version: 2
  test:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
